### ISSUE TITLE
Bug using Output Rename

### ISSUE THREAD

**Issue by pcmodula** [teamQPM/qpm#70] opened 2020-10-11 10:15 UTC
Hi Fernando,
when i use a 32Bit option Rename to and compile (qpm 05_05_19) i obtain this error (i paste  part of c:\errorlog.htm)
<H1 Align=Center>Harbour MiniGUI Errorlog File</H1><BR>
<HR>
<p class="updated">
Date: 09/27/20  Time: 17:49:00<BR>
Application: C:\QPM\QPM.exe<BR>
Time from start: 0 days 0 hours 44 mins 7 secs<BR>
Error MGERROR/0  Control: Radio_OutputCopyMove Of WinPSettings Not defined. Program terminated.</p>
<details><summary>
--------------------------------- Stack Trace ---------------------------------
<br/></summary>
Called from MSGMINIGUIERROR(100) in module: h_error.prg
<BR>
Called from VERIFYCONTROLDEFINED(6002) in module: h_controlmisc.prg
<BR>
Called from GETPROPERTY(4820) in module: h_controlmisc.prg
<BR>
Called from PROJECTSETTINGSSAVE(492) in module: C:\QPMdev\qpm\QPM_ProjectSettings.PRG
<BR>
Called from (b)PROJECTSETTINGS(379) in module: C:\QPMdev\qpm\QPM_ProjectSettings.PRG
<BR>
Called from _DOCONTROLEVENTPROCEDURE(1901) in module: h_windows.prg
<BR>
Called from EVENTS(1839) in module: h_events.prg
<BR>
Called from DOMESSAGELOOP(0)
<BR>
Called from _ACTIVATEWINDOW(1514) in module: h_windows.prg
<BR>
Called from PROJECTSETTINGS(396) in module: C:\QPMdev\qpm\QPM_ProjectSettings.PRG
<BR>
Called from (b)QPM_DEFINOMAINMENU(11169) in module: C:\QPMdev\qpm\QPM.PRG
<BR>
Called from _DOCONTROLEVENTPROCEDURE(1901) in module: h_windows.prg
<BR>
Called from EVENTS(1760) in module: h_events.prg
<BR>
Called from DOMESSAGELOOP(0)
<BR>
Called from _ACTIVATEWINDOW(1514) in module: h_windows.prg
<BR>
Called from MAIN(2545) in module: C:\QPMdev\qpm\QPM.PRG
<BR>
this fast occour if my code is wrong (Missing hbwapi.h) , but after the patch of code, and compile success occur after few time
of exe running

**Comment by fyurisich** [comment] 2020-10-11 13:38
Thanks for reporting!
I can't reproduce the error.
Please add a full sample and instructions to test.
Regards

**Comment by fyurisich** [comment] 2021-03-06 17:41
I'm closing this issue because it was not possible to reproduce the error and the requested test project was not received.

**Closed as completed by fyurisich** 2021-03-06 17:41 UTC
